[[redirects]]
  from = "/online"
  to = "/trad"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Cache-Control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
