name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RESEND_KEY: ${{ secrets.RESEND_API_KEY }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_API_KEY }}

    steps:
      - name: 📥 Cloner le repo
        uses: actions/checkout@v4

      - name: 🟢 Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Installer les dépendances
        run: npm install

      - name: 🚀 Lancer le projet
        run: node index.js
